[package]
name = "tch-m1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = { git = "https://github.com/LaurentMazare/tch-rs", default-features = false }
